using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace UMSV
{
    public enum DisconnectCause : byte
    {
        [Description("عدم شناسائی مقصد")]
        UnallocatedNumber = 1,
        //This number is not in the routing table or it has no path across the ISDN cloud (network).
        //1. Check routing table to see it the number is available.
        //2. Check to make sure the correct digits were dialed and it is a valid number.

        NoRouteToSpecifiedTransitNetwork = 2,
        //The number was dialed with a transit network code such as 108880 to from AT&T to MCI and there is
        //no route across.

        NoRouteToDestination = 3,
        //The dialed number is in the routing plan, but there is no physical route to the destination.
        //1. The PRI D-Channel may be down at one end or the other.
        //2. The span or WAN is not connected correctly.

        SendSpecialInformationTone = 4,
        //Indicates that the called party cannot be reached for reasons that are of a long term nature and that the
        //special information tone should be returned to the calling party.

        MisdialedTrunkPrefix = 5,
        //Indicates the erroneous inclusion of a trunk prefix in the called party number.

        ChannelUnacceptable = 6,
        //Indicates that the channel most recently identified is not acceptable to the sending entity for use in this
        //call.

        CallAwardedAndBeingDeliveredInAnEstablishedChannel = 7,
        //Indicates that the user has been awarded the incoming call, and that the incoming call is being
        //connected to a channel already established to that user for similar calls (e.g. packet-mode virtual calls).

        PreEmption = 8,
        //Indicates that the call is being pre-empted.

        PreEmptionCircuitReservedForReuse = 9,
        //Indicates that the call is being cleared because one of the users involved in the call has requested that
        //the call be cleared.

        [Description("قطع از مقصد")]
        NormalCallClearing = 16,
        //This is one of the most common cause codes and is received for many reasons. It usually occurs
        //because someone hung up the call at one side or the other.

        [Description("اشغالی")]
        UserBusy = 17,
        //The number dialed is busy and cannot receive any more calls.

        [Description("عدم امکان برقراری تماس")]
        NoUserResponding = 18,
        //The called party does not respond to the call, or does not wish to answer the call.

        [Description("عدم پاسخ کاربر")]
        NoAnswerFromUser = 19,
        //The called party has been alerted to the incoming call, but does not respond with a connect indication
        //within a prescribed period of time.
        //NOTE: This cause is not necessarily generated by Q.931 procedures but may be generated by internal
        //network timers.

        [Description("کلاینت آفلاین")]
        SubscriberAbsent = 20,
        //Used when a mobile station has logged off, radio contact is not obtained with a mobile station or if a
        //personal telecommunications user is temporarily not addressable at any user-network interface.

        [Description("رد تماس")]
        CallRejected = 21,
        //Indicates that the equipment sending this cause does not wish to accept this call, alth9ough it could
        //have accepted the call because the equipment sending this cause is neither busy nor incompatible.
        //May also be generated by the network, indicating that the call was cleared due to a supplementary
        //service constraint.

        NumberChanged = 22,
        //This is returned to a calling party when the called party number indicated by the calling party is no
        //longer assigned. The new called party number may optionally be included in the diagnostic field. If a
        //network does not support this cause value, cause number 1 shall be used.

        ExchangeRoutingError = 25,

        NonSelectedUserClearing = 26,
        //Indicates that the user has not been awarded the incoming call.

        DestinationOutOfOrder = 27,
        //This is a working number, but the span to the destination is not active or there is a problem sending
        //messages to this destination.

        InvalidNumberFormat = 28,
        //Indicates that the called party cannot be reached because the called party number is not in a valid
        //format or is not complete. This can happen when you are calling out using a network type number
        //(enterprise) when you should be calling out Unknown or National for the Type of Number (TON).

        FacilityRejected = 29,
        //This cause is returned when a supplementary service requested by the user cannot be provided by the
        //network.

        ResponseToStatusEnquiry = 30,
        //This cause is included in the STATUS message when the reason for generating the STATUS message
        //was the prior receipt of a STATUS ENQUIRY message.

        [Description("قطع از مبدا")]
        NormalUnspecified = 31,
        //This is a very common cause code and happens when the network is not able to determine what to do
        //with the call being made.

        NoCircuitChannelAvailable = 34,
        //There are no B-Channels available to handle the selected call.

        NetworkOutOfOrder = 38,
        //Indicates that the network is not functioning correctly and that the condition is likely to last a relatively
        //long period of time.

        PermanentFrameModeConnectionOutOfService = 39,
        //This cause is included in a STATUS message to indicate that a permanently established frame mode
        //connection is out-of-service.

        PermanentFrameModeConnectionOperational = 40,
        //This cause is included in a STATUS message to indicate that a permanently established frame mode
        //connection is operational and capable of carrying user information.

        TemporaryFailure = 41,
        //The call was disconnected due to a network failure.
        //The network is not functioning correctly and that the condition is not likely to last a long period of time;
        //e.g. the user may wish to try another call attempt almost immediately.

        SwitchingEquipmentCongestion = 42,
        //Indicates that the switching equipment generating this cause is experiencing a period of high traffic.

        AccessInformationDiscarded = 43,
        //Indicates that the network could not deliver access information to the remote user as requested, i.e.
        //user-to-user information, low layer compatibility, high layer compatibility, or sub-address, as indicated
        //in the diagnostic.

        RequestedCircuitChannelNotAvailable = 44,
        //This cause is returned when the circuit or channel indicated by the requesting entity cannot be provided
        //by the other side of the interface.
        //This may happen when you get in a glare condition: Both sides are selected top-down or bottom-up
        //channel hunting.

        ResourceUnavailableUnspecified = 47,
        //Used to report a resource unavailable event only when no other cause in the resource unavailable class
        //applies.

        QualityOfServiceNotAvailable = 49,
        //Used to report that the requested Quality of Service, as defined in Recommendation X.213, cannot be
        //provided (e.g. throughput or transit delay cannot be supported).

        RequestedFacilityNotSubscribed = 50,
        //This cause indicates that the user has requested a supplementary service which is implemented by the
        //equipment which generated this cause, but the user is not authorized to use.

        OutgoingCallsBarredWithinClosedUserGroup = 53,
        //Indicates that although the calling party is a member of the CUG for the outgoing CUG call, outgoing
        //calls are not allowed for this member of the CUG.

        IncomingCallsBarredWithinCUG = 55,
        //Indicates that although the called party is a member of the CUG for the incoming CUG call, incoming
        //calls are not allowed to this member of the CUG.

        BearerCapabilityNotAuthorized = 57,
        //Indicates that the user has requested a bearer capability which is implemented by the equipment, which
        //generated this cause but the user is not authorized to use.

        ABearerCapabilityNotPresentlyAvailable = 58,
        //Indicates that the user has requested a bearer capability, which is implemented by the equipment which
        //generated this cause but which is not available at this time.

        InconsistencyInDesignatedOutgoingAccessInformationAndSubscriberClass = 62,
        //This cause indicates that there is an inconsistency in the designated outgoing access information and
        //subscriber class.

        ServiceOrOptionNotAvailableUnspecified = 63,
        //Used to report a service or option not available event only when no other cause in the serive or option
        //not available class applies.

        BearerCapabilityNotImplemented = 65,
        //Indicates that the equipment sending this cause does not support the bearer capability requested (i.e.
        //requesting 64kb data when only speech is supported).

        ChannelTypeNotImplemented = 66,
        //Indicates that the equipment sending this cause does not support the channel type requested.

        RequestedFacilityNotImplemented = 69,
        //Indicates that the equipment sending this cause does not support the requested supplementary service.

        OnlyRestrictedDigitalInformationBearerCapabilityIsAvailable = 70,
        //Indicates that the calling party has requested an unrestricted (64kb) bearer service but that the
        //equipment sending this cause only supports the restricted version of the requested bearer capability.

        ServiceOrOptionNotImplementedUnspecified = 79,
        //Used to report a service or option not implemented event only when no other cause in the service or
        //option not implemented class applies.

        InvalidCallReferenceValue = 81,
        //Indicates that the equipment sending this cause has received a message with a call reference which is
        //not currently in use or assigned on the user-network interface. E.G. The call that is being reference by
        //this value, does not exist on this system.

        IdentifiedChannelDoesNotExist = 82,
        //Indicates that the equipment sending this cause has received a request to use a channel not activated on
        //the interface for a call.
        //For example, if a user has subscribed to those channels on a PRI numbered from 1 to 12 and the user
        //equipment or the network attempts to use channels 13 through 23, this cause is generated.

        SuspendedCallExistsButThisCallIdentityDoesNot = 83,
        //Indicates that a call resume has been attempted with a call identity which differs from that in use for
        //any presently suspended calls(s).

        CallIdentityInUse = 84,
        //Indicates that the network has received a call suspended request containing a call identity which is
        //already in use for a suspended call within the domain of interfaces over which the call might be
        //resumed.

        NoCallSuspended = 85,
        //Indicates that the network has received a call resume request containing a call identity information
        //element, which presently does not indicate any suspended call within the domain of interfaces over
        //which calls may be resumed.

        CallHavingTheRequestedCallIdentityHasBeenCleared = 86,
        //Indicates that the network has received a call resume request containing a call identity information
        //element indicating a suspended call that has in the meantime been cleared while suspended.

        UserNotMemberOfCUG = 87,
        //Indicates that the called user for the incoming CUG call is not a member of the specified CUG or that
        //the calling user is an ordinary subscriber calling a CUG subscriber.

        IncompatibleDestination = 88,
        //The number being dialed is not capable of the type of call.
        //1. Calling a restricted line in unrestricted mode.
        //2. Calling a pots phone using unrestricted mode.
        //Indicates that the equipment sending this cause has received a request to establish a call which has low
        //layer compatibility, high layer compatibility, or other compatibility attributes which cannot be
        //accommodated.

        NonExistentCUG = 90,
        //Indicates that the specified CUG does not exist.

        InvalidTransitNetworkSelection = 91,
        //Indicates that a transit network identification was received which is of an incorrect format as defined in
        //Annex C/Q.931.

        InvalidMessageUnspecified = 95,
        //Used to report an invalid message event only when no other cause in the invalid message class applies.

        MandatoryInformationElementIsMissing = 96,
        //Indicates that the equipment sending this cause has received a message which is missing an
        //information element which must be present in the message.

        MessageTypeNonExistentOrNotImplemented = 97,
        //Indicates that the equipment sending this cause has received a message with a message type it does not
        //recognize either because this is a message not defined or defined but not implemented by the
        //equipment sending this cause.

        MessageIsNotCompatibleWithTheCallStateOrTheMessageTypeIsNonExistentOrNot = 98,
        //Implemented.
        //Indicates that the equipment sending this cause has received a message such that the procedures do not
        //indicate that this is a permissible message to receive while in the call state, or a STATUS message was
        //received indicating an incompatible call state.

        AnInformationElementOrParameterDoesNotExistOrIsNotImplemented = 99,
        //Indicates that the equipment sending this cause has received a message which includes information
        //element(s)/parameter(s) not recognized because the information element identifier(s)/parameter
        //name(s) are not defined or are defined but not implemented by the equipment sending the cause.

        InvalidInformationElementContents = 100,
        //The call has an information element that is not understood by the switch being called. This cause is
        //usually followed by the information element that is causing the problem.

        TheMessageIsNotCompatibleWithTheCallState = 101,
        //Indicates that a message has been received which is incompatible with the current call state for this call.

        RecoveryOnTimerExpired = 102,
        //This occurs when ISDN messages don’t arrive in specified time according to the Q.931 specification.
        //This cause is sometimes followed by the timer that has expired.

        ParameterNonExistentOrNotImplementedPassedOn = 103,
        //Indicates that the equipment sending this cause has received a message which includes parameters not
        //recognized because the parameters are not defined or are defined but not implemented by the
        //equipment sending the cause.

        MessageWithUnrecognizedParameterDiscarded = 110,
        //Indicates that the equipment sending this cause has discarded a received message, which includes a
        //parameter that is not recognized.

        ProtocolErrorUnspecified = 111,
        //Used to report a protocol error event only when no other cause in the protocol error class applies.

        InterworkingUnspecified = 127,
        //Indicates that there has been interworking with a network which does not provide causes for actions it
        //takes. Thus, the precise cause for a message which is being sent cannot be ascertained

        [Description("مبدا غیر مجاز")]
        SourceIsNotRegistered = 128,

        [Description("خطای ناشناس")]
        UnknownProblem = 129,

        [Description("عدم دسترسی تماس با شماره مورد نظر")]
        NotPrivilegedTarget = 130,

        [Description("قطع شنود")]
        EavesdroppingDisconnected = 131,
    }
}
