#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.Mailbox.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UMSV")]
	public partial class MailboxDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMailbox(Mailbox instance);
    partial void UpdateMailbox(Mailbox instance);
    partial void DeleteMailbox(Mailbox instance);
    partial void InsertMailboxMessage(MailboxMessage instance);
    partial void UpdateMailboxMessage(MailboxMessage instance);
    partial void DeleteMailboxMessage(MailboxMessage instance);
    #endregion
		
		public MailboxDataContext() : 
				base(global::Plugin.Mailbox.Properties.Settings.Default.UMSVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MailboxDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailboxDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailboxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailboxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mailbox> Mailboxes
		{
			get
			{
				return this.GetTable<Mailbox>();
			}
		}
		
		public System.Data.Linq.Table<MailboxMessage> MailboxMessages
		{
			get
			{
				return this.GetTable<MailboxMessage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mailbox")]
	public partial class Mailbox : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BoxNo;
		
		private string _Name;
		
		private string _Password;
		
		private byte _Type;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _ActivationDate;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _CodedPassword;
		
		private System.Nullable<int> _MaxNewMessage;
		
		private System.Nullable<int> _MaxArchiveMessage;
		
		private System.Data.Linq.Binary _WelcomeMessages;
		
		private bool _AutoDequeueFullMailbox;
		
		private System.Nullable<bool> _PagingEnable;
		
		private System.Xml.Linq.XElement _PagingSchedule;
		
		private System.Nullable<bool> _EmailNewMessages;
		
		private int _FollowupCodeStart;
		
		private int _FollowupCodeEnd;
		
		private System.Nullable<int> _MessageNewExpirePeriod;
		
		private System.Nullable<int> _MessageAskExpirePeriod;
		
		private System.Nullable<int> _MessageAnswerExpirePeriod;
		
		private System.Nullable<int> _MessageArchiveExpirePeriod;
		
		private System.Nullable<bool> _AutoArchive;
		
		private System.Nullable<bool> _PlayCallerIDBeforeMessage;
		
		private string _CallerID;
		
		private string _PagingPhone;
		
		private string _Email;
		
		private string _Mobile;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _PostalAddress;
		
		private string _PostalCode;
		
		private string _GraduateLevel;
		
		private string _GraduateField;
		
		private string _FatherName;
		
		private string _IdentityNo;
		
		private string _WorkAddress;
		
		private string _Job;
		
		private string _City;
		
		private System.Nullable<bool> _Gender;
		
		private string _SocialNumber;
		
		private EntitySet<MailboxMessage> _MailboxMessages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBoxNoChanging(string value);
    partial void OnBoxNoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnTypeChanging(byte value);
    partial void OnTypeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnActivationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActivationDateChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnCodedPasswordChanging(string value);
    partial void OnCodedPasswordChanged();
    partial void OnMaxNewMessageChanging(System.Nullable<int> value);
    partial void OnMaxNewMessageChanged();
    partial void OnMaxArchiveMessageChanging(System.Nullable<int> value);
    partial void OnMaxArchiveMessageChanged();
    partial void OnWelcomeMessagesChanging(System.Data.Linq.Binary value);
    partial void OnWelcomeMessagesChanged();
    partial void OnAutoDequeueFullMailboxChanging(bool value);
    partial void OnAutoDequeueFullMailboxChanged();
    partial void OnPagingEnableChanging(System.Nullable<bool> value);
    partial void OnPagingEnableChanged();
    partial void OnPagingScheduleChanging(System.Xml.Linq.XElement value);
    partial void OnPagingScheduleChanged();
    partial void OnEmailNewMessagesChanging(System.Nullable<bool> value);
    partial void OnEmailNewMessagesChanged();
    partial void OnFollowupCodeStartChanging(int value);
    partial void OnFollowupCodeStartChanged();
    partial void OnFollowupCodeEndChanging(int value);
    partial void OnFollowupCodeEndChanged();
    partial void OnMessageNewExpirePeriodChanging(System.Nullable<int> value);
    partial void OnMessageNewExpirePeriodChanged();
    partial void OnMessageAskExpirePeriodChanging(System.Nullable<int> value);
    partial void OnMessageAskExpirePeriodChanged();
    partial void OnMessageAnswerExpirePeriodChanging(System.Nullable<int> value);
    partial void OnMessageAnswerExpirePeriodChanged();
    partial void OnMessageArchiveExpirePeriodChanging(System.Nullable<int> value);
    partial void OnMessageArchiveExpirePeriodChanged();
    partial void OnAutoArchiveChanging(System.Nullable<bool> value);
    partial void OnAutoArchiveChanged();
    partial void OnPlayCallerIDBeforeMessageChanging(System.Nullable<bool> value);
    partial void OnPlayCallerIDBeforeMessageChanged();
    partial void OnCallerIDChanging(string value);
    partial void OnCallerIDChanged();
    partial void OnPagingPhoneChanging(string value);
    partial void OnPagingPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnPostalAddressChanging(string value);
    partial void OnPostalAddressChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnGraduateLevelChanging(string value);
    partial void OnGraduateLevelChanged();
    partial void OnGraduateFieldChanging(string value);
    partial void OnGraduateFieldChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnIdentityNoChanging(string value);
    partial void OnIdentityNoChanged();
    partial void OnWorkAddressChanging(string value);
    partial void OnWorkAddressChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnGenderChanging(System.Nullable<bool> value);
    partial void OnGenderChanged();
    partial void OnSocialNumberChanging(string value);
    partial void OnSocialNumberChanged();
    #endregion
		
		public Mailbox()
		{
			this._MailboxMessages = new EntitySet<MailboxMessage>(new Action<MailboxMessage>(this.attach_MailboxMessages), new Action<MailboxMessage>(this.detach_MailboxMessages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoxNo", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BoxNo
		{
			get
			{
				return this._BoxNo;
			}
			set
			{
				if ((this._BoxNo != value))
				{
					this.OnBoxNoChanging(value);
					this.SendPropertyChanging();
					this._BoxNo = value;
					this.SendPropertyChanged("BoxNo");
					this.OnBoxNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(200)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActivationDate
		{
			get
			{
				return this._ActivationDate;
			}
			set
			{
				if ((this._ActivationDate != value))
				{
					this.OnActivationDateChanging(value);
					this.SendPropertyChanging();
					this._ActivationDate = value;
					this.SendPropertyChanged("ActivationDate");
					this.OnActivationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodedPassword", DbType="VarChar(50)")]
		public string CodedPassword
		{
			get
			{
				return this._CodedPassword;
			}
			set
			{
				if ((this._CodedPassword != value))
				{
					this.OnCodedPasswordChanging(value);
					this.SendPropertyChanging();
					this._CodedPassword = value;
					this.SendPropertyChanged("CodedPassword");
					this.OnCodedPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxNewMessage", DbType="Int")]
		public System.Nullable<int> MaxNewMessage
		{
			get
			{
				return this._MaxNewMessage;
			}
			set
			{
				if ((this._MaxNewMessage != value))
				{
					this.OnMaxNewMessageChanging(value);
					this.SendPropertyChanging();
					this._MaxNewMessage = value;
					this.SendPropertyChanged("MaxNewMessage");
					this.OnMaxNewMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxArchiveMessage", DbType="Int")]
		public System.Nullable<int> MaxArchiveMessage
		{
			get
			{
				return this._MaxArchiveMessage;
			}
			set
			{
				if ((this._MaxArchiveMessage != value))
				{
					this.OnMaxArchiveMessageChanging(value);
					this.SendPropertyChanging();
					this._MaxArchiveMessage = value;
					this.SendPropertyChanged("MaxArchiveMessage");
					this.OnMaxArchiveMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WelcomeMessages", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary WelcomeMessages
		{
			get
			{
				return this._WelcomeMessages;
			}
			set
			{
				if ((this._WelcomeMessages != value))
				{
					this.OnWelcomeMessagesChanging(value);
					this.SendPropertyChanging();
					this._WelcomeMessages = value;
					this.SendPropertyChanged("WelcomeMessages");
					this.OnWelcomeMessagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoDequeueFullMailbox", DbType="Bit NOT NULL")]
		public bool AutoDequeueFullMailbox
		{
			get
			{
				return this._AutoDequeueFullMailbox;
			}
			set
			{
				if ((this._AutoDequeueFullMailbox != value))
				{
					this.OnAutoDequeueFullMailboxChanging(value);
					this.SendPropertyChanging();
					this._AutoDequeueFullMailbox = value;
					this.SendPropertyChanged("AutoDequeueFullMailbox");
					this.OnAutoDequeueFullMailboxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagingEnable", DbType="Bit")]
		public System.Nullable<bool> PagingEnable
		{
			get
			{
				return this._PagingEnable;
			}
			set
			{
				if ((this._PagingEnable != value))
				{
					this.OnPagingEnableChanging(value);
					this.SendPropertyChanging();
					this._PagingEnable = value;
					this.SendPropertyChanged("PagingEnable");
					this.OnPagingEnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagingSchedule", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement PagingSchedule
		{
			get
			{
				return this._PagingSchedule;
			}
			set
			{
				if ((this._PagingSchedule != value))
				{
					this.OnPagingScheduleChanging(value);
					this.SendPropertyChanging();
					this._PagingSchedule = value;
					this.SendPropertyChanged("PagingSchedule");
					this.OnPagingScheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailNewMessages", DbType="Bit")]
		public System.Nullable<bool> EmailNewMessages
		{
			get
			{
				return this._EmailNewMessages;
			}
			set
			{
				if ((this._EmailNewMessages != value))
				{
					this.OnEmailNewMessagesChanging(value);
					this.SendPropertyChanging();
					this._EmailNewMessages = value;
					this.SendPropertyChanged("EmailNewMessages");
					this.OnEmailNewMessagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FollowupCodeStart", DbType="Int NOT NULL")]
		public int FollowupCodeStart
		{
			get
			{
				return this._FollowupCodeStart;
			}
			set
			{
				if ((this._FollowupCodeStart != value))
				{
					this.OnFollowupCodeStartChanging(value);
					this.SendPropertyChanging();
					this._FollowupCodeStart = value;
					this.SendPropertyChanged("FollowupCodeStart");
					this.OnFollowupCodeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FollowupCodeEnd", DbType="Int NOT NULL")]
		public int FollowupCodeEnd
		{
			get
			{
				return this._FollowupCodeEnd;
			}
			set
			{
				if ((this._FollowupCodeEnd != value))
				{
					this.OnFollowupCodeEndChanging(value);
					this.SendPropertyChanging();
					this._FollowupCodeEnd = value;
					this.SendPropertyChanged("FollowupCodeEnd");
					this.OnFollowupCodeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageNewExpirePeriod", DbType="Int")]
		public System.Nullable<int> MessageNewExpirePeriod
		{
			get
			{
				return this._MessageNewExpirePeriod;
			}
			set
			{
				if ((this._MessageNewExpirePeriod != value))
				{
					this.OnMessageNewExpirePeriodChanging(value);
					this.SendPropertyChanging();
					this._MessageNewExpirePeriod = value;
					this.SendPropertyChanged("MessageNewExpirePeriod");
					this.OnMessageNewExpirePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageAskExpirePeriod", DbType="Int")]
		public System.Nullable<int> MessageAskExpirePeriod
		{
			get
			{
				return this._MessageAskExpirePeriod;
			}
			set
			{
				if ((this._MessageAskExpirePeriod != value))
				{
					this.OnMessageAskExpirePeriodChanging(value);
					this.SendPropertyChanging();
					this._MessageAskExpirePeriod = value;
					this.SendPropertyChanged("MessageAskExpirePeriod");
					this.OnMessageAskExpirePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageAnswerExpirePeriod", DbType="Int")]
		public System.Nullable<int> MessageAnswerExpirePeriod
		{
			get
			{
				return this._MessageAnswerExpirePeriod;
			}
			set
			{
				if ((this._MessageAnswerExpirePeriod != value))
				{
					this.OnMessageAnswerExpirePeriodChanging(value);
					this.SendPropertyChanging();
					this._MessageAnswerExpirePeriod = value;
					this.SendPropertyChanged("MessageAnswerExpirePeriod");
					this.OnMessageAnswerExpirePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageArchiveExpirePeriod", DbType="Int")]
		public System.Nullable<int> MessageArchiveExpirePeriod
		{
			get
			{
				return this._MessageArchiveExpirePeriod;
			}
			set
			{
				if ((this._MessageArchiveExpirePeriod != value))
				{
					this.OnMessageArchiveExpirePeriodChanging(value);
					this.SendPropertyChanging();
					this._MessageArchiveExpirePeriod = value;
					this.SendPropertyChanged("MessageArchiveExpirePeriod");
					this.OnMessageArchiveExpirePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoArchive", DbType="Bit")]
		public System.Nullable<bool> AutoArchive
		{
			get
			{
				return this._AutoArchive;
			}
			set
			{
				if ((this._AutoArchive != value))
				{
					this.OnAutoArchiveChanging(value);
					this.SendPropertyChanging();
					this._AutoArchive = value;
					this.SendPropertyChanged("AutoArchive");
					this.OnAutoArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayCallerIDBeforeMessage", DbType="Bit")]
		public System.Nullable<bool> PlayCallerIDBeforeMessage
		{
			get
			{
				return this._PlayCallerIDBeforeMessage;
			}
			set
			{
				if ((this._PlayCallerIDBeforeMessage != value))
				{
					this.OnPlayCallerIDBeforeMessageChanging(value);
					this.SendPropertyChanging();
					this._PlayCallerIDBeforeMessage = value;
					this.SendPropertyChanged("PlayCallerIDBeforeMessage");
					this.OnPlayCallerIDBeforeMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallerID", DbType="VarChar(200)")]
		public string CallerID
		{
			get
			{
				return this._CallerID;
			}
			set
			{
				if ((this._CallerID != value))
				{
					this.OnCallerIDChanging(value);
					this.SendPropertyChanging();
					this._CallerID = value;
					this.SendPropertyChanged("CallerID");
					this.OnCallerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagingPhone", DbType="VarChar(100)")]
		public string PagingPhone
		{
			get
			{
				return this._PagingPhone;
			}
			set
			{
				if ((this._PagingPhone != value))
				{
					this.OnPagingPhoneChanging(value);
					this.SendPropertyChanging();
					this._PagingPhone = value;
					this.SendPropertyChanged("PagingPhone");
					this.OnPagingPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress", DbType="NVarChar(500)")]
		public string PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this.OnPostalAddressChanging(value);
					this.SendPropertyChanging();
					this._PostalAddress = value;
					this.SendPropertyChanged("PostalAddress");
					this.OnPostalAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GraduateLevel", DbType="NVarChar(50)")]
		public string GraduateLevel
		{
			get
			{
				return this._GraduateLevel;
			}
			set
			{
				if ((this._GraduateLevel != value))
				{
					this.OnGraduateLevelChanging(value);
					this.SendPropertyChanging();
					this._GraduateLevel = value;
					this.SendPropertyChanged("GraduateLevel");
					this.OnGraduateLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GraduateField", DbType="NVarChar(50)")]
		public string GraduateField
		{
			get
			{
				return this._GraduateField;
			}
			set
			{
				if ((this._GraduateField != value))
				{
					this.OnGraduateFieldChanging(value);
					this.SendPropertyChanging();
					this._GraduateField = value;
					this.SendPropertyChanged("GraduateField");
					this.OnGraduateFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(50)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityNo", DbType="VarChar(10)")]
		public string IdentityNo
		{
			get
			{
				return this._IdentityNo;
			}
			set
			{
				if ((this._IdentityNo != value))
				{
					this.OnIdentityNoChanging(value);
					this.SendPropertyChanging();
					this._IdentityNo = value;
					this.SendPropertyChanged("IdentityNo");
					this.OnIdentityNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkAddress", DbType="NVarChar(200)")]
		public string WorkAddress
		{
			get
			{
				return this._WorkAddress;
			}
			set
			{
				if ((this._WorkAddress != value))
				{
					this.OnWorkAddressChanging(value);
					this.SendPropertyChanging();
					this._WorkAddress = value;
					this.SendPropertyChanged("WorkAddress");
					this.OnWorkAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(50)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
		public System.Nullable<bool> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocialNumber", DbType="Char(12)")]
		public string SocialNumber
		{
			get
			{
				return this._SocialNumber;
			}
			set
			{
				if ((this._SocialNumber != value))
				{
					this.OnSocialNumberChanging(value);
					this.SendPropertyChanging();
					this._SocialNumber = value;
					this.SendPropertyChanged("SocialNumber");
					this.OnSocialNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mailbox_MailboxMessage", Storage="_MailboxMessages", ThisKey="BoxNo", OtherKey="BoxNo")]
		public EntitySet<MailboxMessage> MailboxMessages
		{
			get
			{
				return this._MailboxMessages;
			}
			set
			{
				this._MailboxMessages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MailboxMessages(MailboxMessage entity)
		{
			this.SendPropertyChanging();
			entity.Mailbox = this;
		}
		
		private void detach_MailboxMessages(MailboxMessage entity)
		{
			this.SendPropertyChanging();
			entity.Mailbox = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MailboxMessage")]
	public partial class MailboxMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BoxNo;
		
		private string _Sender;
		
		private System.DateTime _ReceiveTime;
		
		private System.Data.Linq.Binary _Data;
		
		private byte _Type;
		
		private System.Nullable<int> _FollowupCode;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _ExpireDate;
		
		private EntityRef<Mailbox> _Mailbox;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBoxNoChanging(string value);
    partial void OnBoxNoChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnReceiveTimeChanging(System.DateTime value);
    partial void OnReceiveTimeChanged();
    partial void OnDataChanging(System.Data.Linq.Binary value);
    partial void OnDataChanged();
    partial void OnTypeChanging(byte value);
    partial void OnTypeChanged();
    partial void OnFollowupCodeChanging(System.Nullable<int> value);
    partial void OnFollowupCodeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnExpireDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpireDateChanged();
    #endregion
		
		public MailboxMessage()
		{
			this._Mailbox = default(EntityRef<Mailbox>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoxNo", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string BoxNo
		{
			get
			{
				return this._BoxNo;
			}
			set
			{
				if ((this._BoxNo != value))
				{
					if (this._Mailbox.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBoxNoChanging(value);
					this.SendPropertyChanging();
					this._BoxNo = value;
					this.SendPropertyChanged("BoxNo");
					this.OnBoxNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="VarChar(15)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveTime", DbType="DateTime NOT NULL")]
		public System.DateTime ReceiveTime
		{
			get
			{
				return this._ReceiveTime;
			}
			set
			{
				if ((this._ReceiveTime != value))
				{
					this.OnReceiveTimeChanging(value);
					this.SendPropertyChanging();
					this._ReceiveTime = value;
					this.SendPropertyChanged("ReceiveTime");
					this.OnReceiveTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FollowupCode", DbType="Int")]
		public System.Nullable<int> FollowupCode
		{
			get
			{
				return this._FollowupCode;
			}
			set
			{
				if ((this._FollowupCode != value))
				{
					this.OnFollowupCodeChanging(value);
					this.SendPropertyChanging();
					this._FollowupCode = value;
					this.SendPropertyChanged("FollowupCode");
					this.OnFollowupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(200)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpireDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpireDate
		{
			get
			{
				return this._ExpireDate;
			}
			set
			{
				if ((this._ExpireDate != value))
				{
					this.OnExpireDateChanging(value);
					this.SendPropertyChanging();
					this._ExpireDate = value;
					this.SendPropertyChanged("ExpireDate");
					this.OnExpireDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mailbox_MailboxMessage", Storage="_Mailbox", ThisKey="BoxNo", OtherKey="BoxNo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mailbox Mailbox
		{
			get
			{
				return this._Mailbox.Entity;
			}
			set
			{
				Mailbox previousValue = this._Mailbox.Entity;
				if (((previousValue != value) 
							|| (this._Mailbox.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mailbox.Entity = null;
						previousValue.MailboxMessages.Remove(this);
					}
					this._Mailbox.Entity = value;
					if ((value != null))
					{
						value.MailboxMessages.Add(this);
						this._BoxNo = value.BoxNo;
					}
					else
					{
						this._BoxNo = default(string);
					}
					this.SendPropertyChanged("Mailbox");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
